// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHGvJZkYQGHb7VyEZPrqnCmH1NN8NXN3w',
    appId: '1:584267138091:web:61d71e3b0aa1d24ec2d66e',
    messagingSenderId: '584267138091',
    projectId: 'chatapp3-f4163',
    authDomain: 'chatapp3-f4163.firebaseapp.com',
    storageBucket: 'chatapp3-f4163.appspot.com',
    measurementId: 'G-MD7Z70K1Z7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlVoOuZlLOyut5XbL3B3IoUXErcBeExj8',
    appId: '1:584267138091:android:f8ff0605fc22a82cc2d66e',
    messagingSenderId: '584267138091',
    projectId: 'chatapp3-f4163',
    storageBucket: 'chatapp3-f4163.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWZjT-o7LhAomcjHszcCNf9s-SCKwC6zk',
    appId: '1:584267138091:ios:8f716737d158d8d3c2d66e',
    messagingSenderId: '584267138091',
    projectId: 'chatapp3-f4163',
    storageBucket: 'chatapp3-f4163.appspot.com',
    iosBundleId: 'com.example.chatapp3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHGvJZkYQGHb7VyEZPrqnCmH1NN8NXN3w',
    appId: '1:584267138091:web:9c04ac1900824a38c2d66e',
    messagingSenderId: '584267138091',
    projectId: 'chatapp3-f4163',
    authDomain: 'chatapp3-f4163.firebaseapp.com',
    storageBucket: 'chatapp3-f4163.appspot.com',
    measurementId: 'G-T6MV3MBD1Z',
  );
}
